FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ideaSharing

ideaSharing is a platform for sharing ideas to public.


# Group User

Resource Define

    {
        "id": "number",
        "username": "string",
        "email": "string",
        "password": "string",
        "description": "string"
    }


## /api/users

### POST

Create a user.

+ Request (application/json)

        {
            "username": "user1",
            "password": "passw",
            "email": "user1@gmail.com",
            "description": "This is user1"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "user1",
            "email": "user1@gmail.com",
            "description": "This is user1"
        }


## /api/users/{id}

### GET

Get the user by id.

+ Parameters

    + id: `1` (number, required)
    
+ Response 200 (application/json)

        {
            "id": 1,
            "username": "user1",
            "email": "user1@gmail.com",
            "description": "This is user1"
        }

### POST

Update a user.

+ Request (application/json)

        {
            "description": "user1 is awesome"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "user1",
            "email": "user1@gmail.com",
            "description": "user1 is awsome"
        }


# Group Idea

Resource Define

    {
        "id": "number",
        "user_id": "number",
        "title": "string",
        "description": "string",
        "problem": "string",
        "solution": "string"
    }
    
## /api/users/{user_id}/ideas

### GET

Get user's ideas.

+ Parameters

    + user_id: `1` (number, required)

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "user_id": 1,
                "title": "Fly Jacket",
                "description": "This is a jacket which enable flying",
                "problem": "People cannot fly",
                "solution": "Use Fly Jacket"
            }
        ]
        
### POST

Create an idea.

+ Parameters

    + user_id: `1` (number, required)

+ Attributes

    + title (string, required)
    + description (string, required)
    + problem (string, required)
    + solution (string, required)

+ Request (application/json)

        {
            "title": "Fly Jacket",
            "description": "This is a jacket which enable flying",
            "problem": "People cannot fly",
            "solution": "Use Fly Jacket"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "user_id": 1,
            "title": "Fly Jacket",
            "description": "This is a jacket which enable flying",
            "problem": "People cannot fly",
            "solution": "Use Fly Jacket"
        }


## /api/users/{user_id}/ideas/{id}

### GET

Get the idea.

+ Parameters

    + user_id: `1` (number, required)
    + id: `1` (number, required)
    
+ Response 200 (application/json)

        {
            "id": 1,
            "user_id": 1,
            "title": "Fly Jacket",
            "description": "This is a jacket which enable flying",
            "problem": "People cannot fly",
            "solution": "Use Fly Jacket"
        }

### POST

Update the idea.

+ Request (application/json)

        {
            "title": "Awesome Flying Jacket"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "user_id": 1,
            "title": "Awesome Flying Jacket",
            "description": "This is a jacket which enable flying",
            "problem": "People cannot fly",
            "solution": "Use Fly Jacket"
        }


# Group Pages

## /register

Get register page

### GET

+ Response 200 (text/html)


## /login

Get login page

### GET

+ Response 200 (text/html)

## /logout

Get logout page

### GET

+ Response 200 (text/html)