FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ideaSharing

ideaSharing is a platform for sharing ideas to public.


# Group User

Resource Define

    {
        "id": "number",
        "username": "string",
        "email": "string",
        "password": "string",
        "description": "string"
    }


## /api/users

### POST

Create a user.

+ Request (application/json)

        {
            "username": "user1",
            "password": "passw",
            "email": "user1@gmail.com",
            "description": "This is user1"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "user1",
            "email": "user1@gmail.com",
            "description": "This is user1"
        }


## /api/users/{id}

### GET

Get the user by id.

+ Parameters

    + id: `1` (number, required)
    
+ Response 200 (application/json)

        {
            "id": 1,
            "username": "user1",
            "email": "user1@gmail.com",
            "description": "This is user1"
        }

### POST

Update a user.

+ Request (application/json)

        {
            "description": "user1 is awesome"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "user1",
            "email": "user1@gmail.com",
            "description": "user1 is awsome"
        }


# Group Idea

Resource Define

    {
        "id": "number",
        "user_id": "number",
        "category_id": "number",
        "title": "string",
        "description": "string",
        "problem": "string",
        "solution": "string"
    }
    
## /api/ideas{?user_id}

### GET

Get user's ideas.

+ Parameters

    + user_id: `1` (number, required)

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "user_id": 1,
                "category_id": 1,
                "title": "Fly Jacket",
                "description": "This is a jacket which enable flying",
                "problem": "People cannot fly",
                "solution": "Use Fly Jacket"
            }
        ]
        
### POST

Create an idea.

+ Parameters

    + user_id: `1` (number, required)

+ Attributes

    + title (string, required)
    + category_id (number, optional)
    + description (string, required)
    + problem (string, required)
    + solution (string, required)

+ Request (application/json)

        {
            "category_id": 1,
            "title": "Fly Jacket",
            "description": "This is a jacket which enable flying",
            "problem": "People cannot fly",
            "solution": "Use Fly Jacket"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "user_id": 1,
            "category_id": 1,
            "title": "Fly Jacket",
            "description": "This is a jacket which enable flying",
            "problem": "People cannot fly",
            "solution": "Use Fly Jacket"
        }


## /api/ideas/{id}

### GET

Get the idea.

+ Parameters

    + id: `1` (number, optional)
    
+ Response 200 (application/json)

        {
            "id": 1,
            "user_id": 1,
            "category_id": 1,
            "title": "Fly Jacket",
            "description": "This is a jacket which enable flying",
            "problem": "People cannot fly",
            "solution": "Use Fly Jacket"
        }

### POST

Update the idea.

+ Request (application/json)

        {
            "title": "Awesome Flying Jacket"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "user_id": 1,
            "category_id": 1,
            "title": "Fly Jacket",
            "description": "This is a jacket which enable flying",
            "problem": "People cannot fly",
            "solution": "Use Fly Jacket"
        }

# Group Category

Resource Defination

    {
        "id": "number",
        "name": "number"
    }
    

## /api/categories

### GET

Get all categories.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "technology"
            }
        ]

### POST

Create a category.

+ Attributes

    + name (string, required)

+ Request (application/json)

        {
            "name": "technology"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "technology"
        }
        
## /api/categories/{id}

### GET

Get the category.

+ Parameters

    + id: `1` (number, required)

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "technology"
        }

# Group Comment

Resource Defination

    {
        "id": "number",
        "idea_id": "number",
        "commenter_id": "number",
        "time": "datetime",
        "content": "string"
    }

## /api/ideas/{idea_id}/comments

### GET

Get all comments (of an idea).

+ Parameters

    + idea_id: `1` (number, required)

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "idea_id": 1,
                "commenter_id": 1,
                "time": 2015-11-23 15:00:00 (Not sure),
                "content": "This idea is fantastic"
            }
        ]

### POST

Create a comment.

+ Parameters

    + idea_id: `1` (number, required)

+ Request (application/json)

        {
            "commenter_id": 1,
            "time": 2015-11-23 15:00:00 (Not sure),
            "content": "This idea is fantastic"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "idea_id": 1,
            "commenter_id": 1,
            "time": 2015-11-23 15:00:00 (Not sure),
            "content": "This idea is fantastic"
        }
        
## /api/ideas/{idea_id}/comments/{id}

### GET

Get the comment.

+ Parameters

    + idea_id: `1` (number, required)
    + id: `1` (number, required)

+ Response 200 (application/json)

        {
            "id": 1,
            "idea_id": 1,
            "commenter_id": 1,
            "time": 2015-11-23 15:00:00 (Not sure),
            "content": "This idea is fantastic"
        }

# Group Pages

## /register

Get register page

### GET

+ Response 200 (text/html)


## /login

Get login page

### GET

+ Response 200 (text/html)

## /logout

Get logout page

### GET

+ Response 200 (text/html)